config/routes.rb
CookbookApp::Application.routes.draw do

  root :to => 'welcome#index'
resources :recipes
resources :ingredients
resources :cookbooks

end

app/models/cookbook.rb
# == Schema Information
#
# Table name: cookbooks
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  cuisine     :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  isbn        :integer
#

class Cookbook < ActiveRecord::Base
  attr_accessible :cuisine, :description, :title, :isbn, :recipe_ids

  has_many :recipes, inverse_of: :cookbook
  has_many :ingredients, through: :recipes

  validates_uniqueness_of :title, :isbn
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  measurement :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ingredient < ActiveRecord::Base
  attr_accessible :measurement, :name, :recipe_ids

  has_and_belongs_to_many :recipes
  has_many :cookbooks, through: :recipes

end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  instructions :text
#  name         :string(255)
#  serving_size :integer
#  image_url    :text
#  course       :integer
#  cook_time    :text
#  cookbook_id  :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Recipe < ActiveRecord::Base
  attr_accessible :cook_time, :course, :image_url, :instructions, :name, :serving_size, :cookbook_id

  belongs_to :cookbook, inverse_of: :recipes
  has_and_belongs_to_many :ingredients
  # validates :serving_size, :numericality => { :greater_than "0" }
  # validates :cook_time, :numericality => { :greater_than "0" }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController
  def index
    @cookbooks = Cookbook.all
    # render index
  end
  def create
    cookbook = Cookbook.new(params['cookbook']) #params cookbook because we are dealing with the forms fields people enter
    if cookbook.save
      redirect_to cookbooks_path
    else
      redirect_to new_cookbook_path
    end
    # # Cookbook.create(:title => 'Cooking with fish', :cuisine => 'fishy', :descripion => 'A book about...')
    # redirect_to cookbooks_path
    #  # render :create
  end
  def new
    @cookbook = Cookbook.new
    @recipes = Recipe.all
    # render :new
  end
  def edit
    @cookbook = Cookbook.find(params[:id])
    @recipes = Recipe.all

    # render :edit
  end
  def show
    @cookbook = Cookbook.find(params[:id])   #@cookbook instance variable here just needs to be consistent when referneced. Can be anything.
    # render :show           capitalized Cookbook. is not arbitrary. Must be exact class name.
  end
  def update
    cookbook = Cookbook.find(params['id'])  # this is params id because it's the id in the url--which book are we talking about?
    if cookbook.update_attributes(params["cookbook"])  #yes, an action is happening in the condition
      redirect_to cookbooks_path
    else
      # We need to give feedback if unsuccessful
      redirect_to edit_cookbook_path
    end
    # render :update
  end
  def destroy
    Cookbook.find(params[:id]).delete  #no instance variable required--we are throwing it away
    redirect_to cookbooks_path
    # render :destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	  def index
#render :index
	  end

	end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def create
    ingredient = Ingredient.new(params[:ingredient])
    if ingredient.save
      redirect_to ingredients_path
    else
      redirect_to new_ingredient_path
    end
  end

  def new
    @ingredient = Ingredient.new
    @recipes = Recipe.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
    @recipes = Recipe.all

  end

  def update
    ingredient = Ingredient.find(params[:id])
    if ingredient.update_attributes(params['ingredient'])
      redirect_to ingredients_path
    else
      redirect_to edit_ingredient_path
    end

  end

  def destroy
    Ingredient.find(params[:id]).delete
    redirect_to ingredients_path
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def create
    recipe = Recipe.new(params[:recipe])
    if recipe.save
      redirect_to recipes_path
    else
      redirect_to new_recipe_path
    end
  end

  def new
    @recipe = Recipe.new
  end

  def show
  	    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    recipe = Recipe.find(params[:id])
    if recipe.update_attributes(params['recipe'])
      redirect_to recipes_path
    else
      redirect_to edit_recipe_path
    end

  end

  def destroy
  	    Recipe.find(params[:id]).delete
  	    redirect_to recipes_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render text: 'welcome to our Cookbook!'    #the parameter of the render method is a hash
  end                #just saying render text but no template. render just text.
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cookbooks/_form.html.erb
<%= form_for @cookbook do |f| %>
<%= f.label :title %>
<%= f.text_field :title %><br>
<%= f.label :cuisine %>
<%= f.text_field :cuisine %><br>
<%= f.label :description %>
<%= f.text_field :description %><br>
<%= f.submit %>

<% end %>

app/views/cookbooks/edit.html.erb
<%= render partial: 'cookbooks/partials/form' %>

app/views/cookbooks/index.html.erb
<ul>
	<% @cookbooks.each do |cookbook| %>
	<p><%= link_to cookbook.title, cookbook %></p>
	<li>
		<p> Title: <%= cookbook.title %></p>
		<p> Cuisine: <%= cookbook.cuisine %></p>
		<p> Description: <%= cookbook.description %></p>
	</li>
	<% end %>
</ul>

app/views/cookbooks/new.html.erb
<%= render partial: 'cookbooks/partials/form' %>

app/views/cookbooks/partials/_form.html.erb
<%= form_for @cookbook do |f| %>
<%= f.label :title %>
<%= f.text_field :title %><br>
<%= f.label :cuisine %>
<%= f.text_field :cuisine %><br>
<%= f.label :description %>
<%= f.text_field :description %><br>

<% @recipes.each do |recipe| %>
<%= recipe.name %>
<%= check_box_tag 'cookbook[recipe_ids][]', recipe.id, recipe.in?(@cookbook.recipes.to_a) %>
<% end %>

<%= f.submit %>
<% end %>

app/views/cookbooks/show.html.erb
<p> Title: <%= @cookbook.title %></p>
<p>Cuisine: <%= @cookbook.cuisine %></p>
<p>Description: <%= @cookbook.description %></p>

<%= button_to 'Edit', edit_cookbook_path(@cookbook), method: 'get' %>
<%= button_to 'Delete', cookbook_path(@cookbook), method: 'delete' %>

app/views/home/index.html.erb
<h1>Hi! Welcome to the Cookbook site!</h1>

app/views/ingredients/edit.html.erb
<%= render partial: 'ingredients/partials/form' %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>
<% @ingredients.each do |ingredient| %>

<p><%= link_to ingredient.name, ingredient %></p>
<p>Name: <%= ingredient.name %></p>
<p>Measurement: <%= ingredient.measurement %></p>
<% end %>

app/views/ingredients/new.html.erb
<%= render partial: 'ingredients/partials/form' %>

app/views/ingredients/partials/_form.html.erb
<%= form_for @ingredient do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :measurement %>
<%= f.text_field :measurement %>

<% @recipes.each do |recipe| %>
<%= recipe.name %>
<%= check_box_tag 'ingredient[recipe_ids][]', recipe.id, recipe.in?(@ingredient.recipes.to_a) %>
<% end %>


<%= f.submit %>
<% end %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %>
<p>Name: <%= @ingredient.name %> </p>
<p>Measurement: <%= @ingredient.measurement %> </p>
<p>In Recipes: 
<p>
	<% @ingredient.recipes do |recipe|%>
  <%= recipe.name %>
	<% end %>
</p>
<%= button_to 'Edit', edit_ingredient_path(@ingredient), method: 'get' %>
<%= button_to 'Delete', ingredient_path(@ingredient), method: 'delete' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookbookApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "/layouts/partials/nav.html.erb" %>
<%= yield %>

</body>
</html>

app/views/layouts/partials/_nav.html.erb
<nav>
<ul>
<li><%= link_to 'Cookbooks', cookbooks_path %></li>
<li><%= link_to 'New Cookbooks', new_cookbook_path %></li>
<li><%= link_to 'Recipes', recipes_path %></li>
<li><%= link_to 'New Recipes', new_recipe_path %></li>
<li><%= link_to 'Ingredients', ingredients_path %></li>
<li><%= link_to 'New Ingredients', new_ingredient_path %></li>
</ul>
</nav>

app/views/recipes/edit.html.erb
<%= render partial: 'recipes/partials/form' %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<% @recipes.each do |recipe| %>

<p><%= link_to recipe.name, recipe %></p>
<p>Instructions: <%= recipe.instructions %></p>
<p>Serving Size: <%= recipe.serving_size %></p>
<p>Course: <%= recipe.course %></p>
<p>Cook Time: <%= recipe.cook_time %></p>
<p><img src="<%= recipe.image_url %>" alt="food picture"</p>
<% end %>

app/views/recipes/new.html.erb
<%= render partial: 'recipes/partials/form' %>

app/views/recipes/partials/_form.html.erb
<%= form_for @recipe do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :cook_time %>
<%= f.number_field :cook_time %>
<%= f.label :serving_size %>
<%= f.number_field :serving_size %>
<%= f.label :instructions %>
<%= f.text_field :instructions %>
<%= f.label :image_url %>
<%= f.text_field :image_url %>
<%= f.label :course %>
<%= f.text_field :course %>
<%= f.label :cookbook_id %>
<%= f.select :cookbook_id, Cookbook.all.map{ |cookbook| [cookbook.title, cookbook.id]} %>
<%= f.submit %>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %>
<p>Course: <%= @recipe.course %> </p>
<p>Cooktime: <%= @recipe.cook_time %> </p>
<p>Instructions: <%= @recipe.instructions %></p>
<img src=<%= @recipe.image_url %> />
<p>From Cookbook: 
<p>
	<% if @recipe.cookbook.present? %>
	<%= link_to @recipe.cookbook.title, @recipe.cookbook %>
	<% else %>
	Not yet published.
	<% end %>
</p>
<%= button_to 'Edit', edit_recipe_path(@recipe), method: 'get' %>
<%= button_to 'Delete', recipe_path(@recipe), method: 'delete' %>